### ISSUE TITLE
Update API CORS headers for thumbnail images to render StackBlitz images

### ISSUE THREAD

**Issue by adamjarling** [nulib/dc-api-v2#178]
When setting up a [StackBlitz](https://stackblitz.com/fork/github/canopy-iiif/canopy-iiif) demo environment for our IIIF Workshop, we've noticed that Chromium browsers display NUL DC API `/thumbnail` images fine, however Firefox and Safari cannot render the images due to CORS.

![image](https://github.com/nulib/dc-api-v2/assets/3020266/d56960f8-06a0-4860-ab1f-de31b398a2ef)

**From MBK**

> That’s kinda weird. Why would an image be blocked by CORS? Anyway, it’s possible that Stackblitz is using different CORS rules than regular browsers do. I wasn’t aware of the Cross-Origin-Resource-Policy (or the related Cross-Origin-Embedder-Policy) headers before, but it wouldn’t hurt to add them to our [CORS helper function](https://github.com/nulib/dc-api-v2/blob/deploy/staging/src/helpers.js#L55-L68).

Note:

Canopy uses the `/thumbnail` route (Search results, Sliders) and leverages the iiif image service endpoint where applicable (Viewer, Hero images).

https://api.dc.library.northwestern.edu/api/v2/works/cd5e1b9c-370b-40e5-b3d9-defc1d8e0777/thumbnail
https://iiif.dc.library.northwestern.edu/iiif/2/8335ca0b-e08f-41d3-9e0c-d9feeaec9ccd/full/1917,/0/default.jpg 

## Done Looks Like
- [ ] CORS helper function updated
- [ ] Test again in StackBlitz to see if images render in Safari and Firefox

**Comment by kdid** [comment]
Hey @adamjarling  & @mathewjordan  - can you try adding crossorigin to the images before we resort to updating the API (and potentially the IIIF server as well). There's some docs about it: https://blog.stackblitz.com/posts/cross-browser-with-coop-coep/ (not super easy to read), But also if you try this thing someone made but use one of our images (and remove the styles so you can see it) -- doesn't it work, it seemed to me like it did? https://stackblitz.com/edit/cors-corp-image-example?file=src%2Findex.html If not, let us know and we can take a look at the other route.

**Comment by bmquinn** [comment]
abandoned.
